# Generated by Django 4.2.5 on 2023-11-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_department_studentid_alter_recipe_recipe_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='vege.studentid'),
        ),
    ]
