# Generated by Django 4.2.6 on 2023-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subject_subject_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject_marks',
            new_name='SubjectMarks',
        ),
    ]
